name: CI

on: push


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v12

      - run: make install

      - run: make lint

      - name: run tests
        run: make test
